accounts/urls.py
from django.urls import path

from .views import UserRegistrationView, LogoutView, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
]

api/urls.py
# api_app/urls.py
from django.urls import path
from .views import UserBankAccountView, APIListView, TransactionListView

app_name = 'api_app'

urlpatterns = [
    path('celestial/report/', TransactionListView.as_view(), name='transaction-report'),
    path('api-list/', APIListView.as_view(), name='api-list'),
    path('user/balance/', UserBankAccountView.as_view(), name='user-balance'),
    path('celestial/report/<str:daterange>/', TransactionListView.as_view(), name='transaction-report-filtered'),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import (TokenObtainPairView, TokenRefreshView,TokenVerifyView)

from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    ),
    path('api/', include('api.urls')),
    path('auditoria/', include('core.urls')),

    # Tokens
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

core/urls.py
from django.urls import path
from .views import record_auditoria_api
app_name = 'api_auditoria'

urlpatterns = [
    path('record/<str:evento>/<str:nivel>/', record_auditoria_api, name='record_auditoria_api'),
]

transactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
]

core/models.py
from django.db import models
from django.conf import settings

class Auditoria(models.Model):
    evento_choices = [
        ('login', 'Inicio de sesión'),
        ('transaccion', 'Transacción'),
        ('retiro', 'Retiro'),
        ('deposito', 'Deposito')

    ]
    EVENTO_NIVEL_CHOICES = [
        ('normal', 'Normal'),
        ('medio', 'Medio'),
        ('alto', 'Alto'),
    ]

    nro = models.AutoField(primary_key=True)
    fecha_hora = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField()
    servidor = models.CharField(max_length=255)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    evento = models.CharField(max_length=20, choices=evento_choices)
    nivel = models.CharField(max_length=20, choices=EVENTO_NIVEL_CHOICES)
    mac = models.CharField(max_length=17)
    origin = models.GenericIPAddressField()


    def __str__(self):
        return f'{self.fecha_hora} - {self.evento} - Usuario: {self.usuario.username}'

core/views.py
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Auditoria
from .serializers import AuditoriaSerializer
from uuid import getnode as get_mac

class HomeView(TemplateView):
    template_name = 'core/index.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated:
            return redirect('/transactions/report/')
        return super().dispatch(request, *args, **kwargs)




@api_view(['POST'])
def record_auditoria_api(request, evento, nivel):
    mac_int = get_mac()
    dir_mac = ':'.join(("%012X" % mac_int)[i:i + 2] for i in range(0, 12, 2))
    origin = request.META.get('HTTP_ORIGIN', '')
    ip = request.data.get('ip', '')

    # Crear una instancia de Auditoria
    auditoria_instance = Auditoria(
        ip=ip,
        servidor=request.META.get('COMPUTERNAME', ''),
        usuario=request.user,
        evento=evento,
        nivel=nivel,
        mac=dir_mac,
        origin=origin,
    )

    # Guardar la instancia en la base de datos
    auditoria_instance.save()

    # Serializar y devolver la respuesta
    serializer = AuditoriaSerializer(auditoria_instance)
    return Response(serializer.data)

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Dummy Banking System" />
        <meta name="author" content="Maksudul Haque" />
        <title>
            {% block head_title %}Banking System{% endblock %}
        </title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        {% block head_extra %}{% endblock %}
        <style>
            html,
            body {
                height: 100%;
                width: 100%;
            }
            
            body {
                background-image: url('{% static "img/wp-1.jpg" %}');
                background-repeat: no-repeat;
                background-size: cover;
                background-position: center center;
                padding-bottom: 5em;
            }
            body #main{
                padding-bottom: 5em;
            }
            
            footer {
                position: fixed !important;
                bottom: 0 !important;
                width: 100%;
            }
            /* Estilos para el Modal */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0,0,0,0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 500px;
        height: auto;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
        border-radius: 10px;
    }

    .modal-header {
        padding: 2px 16px;
        background-color: #fefefe;
        color: #008CBA;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    button {
        background-color: #008CBA;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
    }

    button:hover {
        opacity: 0.8;
    }


    input[type=email], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }

    </style>
    </head>
    <body class="bg-gray-100">
        {% block body %}
            {% include 'core/navbar.html' %}
            <div class="lg:container lg:mx-auto" id="main">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
            {% include 'core/footer.html' %}

        {% endblock %}
        {% block footer_extra %}{% endblock %}


    <!-- Script para mostrar/ocultar menú en pantallas más pequeñas -->
    <script>
        $(document).ready(function () {
            $('.lg\\:hidden').on('click', function () {
                $('.lg\\:flex').toggleClass('hidden');
            });
        });
    </script>

    </body>

</html>

templates/core/footer.html
<footer class="footer bg-blue-900 text-white relative pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-0 pb-2">
                <p class="text-md text-white font-bold mb-2">
                    © {% now "Y" %} Celestial Bank | Todos los derechos reservados | Aviso legal | Política de privacidad
                </p>
            </div>
        </div>
    </div>
</footer>

templates/core/index.html
{% extends 'core/base.html' %} {% load static %} {% block head_title %}Banking System{% endblock %} {% block content %}
<div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">

    <div class="w-full lg:w-1/2 lg:py-6 text-center">
        <h1 style="font-size: 12rem" class="font-black text-blue-900 text-opacity-50">&#x20B1;&#x20B1;</h1>
    </div>
    <div class="flex flex-col w-full lg:w-1/2 justify-center items-start pt-12 pb-24 px-6 bg-white rounded-2xl bg-opacity-70">
        <h1 class="font-bold text-4xl my-4">Celestial Bank</h1>
        <p class="leading-normal mb-4">
            Celestial Bank es más que un banco; es un reflejo del universo de posibilidades financieras.
            Nuestro compromiso radica en elevar tus sueños y metas hacia alturas cósmicas,
            brindando servicios de vanguardia que te ayuden a alcanzar el éxito en tu viaje financiero.
            Con una visión estelar y valores arraigados en la excelencia, estamos aquí para iluminar tu camino hacia un
            futuro próspero y brillante. En Celestial Bank, cada transacción es un paso hacia las estrellas,
            impulsando tu trayecto hacia la grandeza económica.
        </p>
        <div class="flex justify-end w-full">
            <a href="{% url 'accounts:user_registration' %}" class="bg-blue-900 text-white rounded-none hover:bg-white hover:text-blue-900 hover:border-blue-900 shadow hover:shadow-lg py-2 px-4 border border-gray-900 hover:border-transparent">Registrarse</a>
        </div>
    </div>
</div>

{% endblock %}

templates/core/messages.html
{% for message in messages %}
<div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" role="alert">
    <div class="flex">
        <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
        <div>
            <p class="font-bold">Success!</p>
            <p class="text-sm">{{ message }}</p>
        </div>
    </div>
</div>
{% endfor %}

templates/core/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-blue-400 p-6 px-10">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight text-white">Celestial Bank</span>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto px-10">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                <a href="{% url 'transactions:transaction_report' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Inicio
                </a>
                <a href="{% url 'transactions:deposit_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Depósito
                </a>
                <a href="{% url 'transactions:withdraw_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Retirar
                </a>
            </div>
            <div class="flex w-auto ">
                <div class="text-blue-1200 my-aut font-black px-5">Bienvenido, {{ request.user.first_name }} {{ request.user.last_name }}!</div>
                <a href="{% url 'accounts:user_logout' %}" class="mx-2 inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Cerrar sesión</a>
            </div>
        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'accounts:user_login' %}" class="mr-2 inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Acceder</a>
            </div>
            <div>
                <a href="{% url 'accounts:user_registration' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Registrar</a>
            </div>
        {% endif %}
    </div>
</nav>