api/urls.py
# api_app/urls.py
from django.urls import path
from .views import UserBankAccountView, APIListView, TransactionListView

app_name = 'api_app'

urlpatterns = [
    path('celestial/report/', TransactionListView.as_view(), name='transaction-report'),
    path('api-list/', APIListView.as_view(), name='api-list'),
    path('user/balance/', UserBankAccountView.as_view(), name='user-balance'),
    path('celestial/report/<str:daterange>/', TransactionListView.as_view(), name='transaction-report-filtered'),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import (TokenObtainPairView, TokenRefreshView,TokenVerifyView)

from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    ),
    path('api/', include('api.urls')),
    path('auditoria/', include('core.urls')),

    # Tokens
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

transactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
]

transactions/models.py
from django.db import models

from .constants import TRANSACTION_TYPE_CHOICES
from accounts.models import UserBankAccount


class Transaction(models.Model):
    account = models.ForeignKey(
        UserBankAccount,
        related_name='transactions',
        on_delete=models.CASCADE,
    )
    #cantidad de la transacción
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    #saldo después de la transaccion
    balance_after_transaction = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE_CHOICES
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    origin = models.CharField(max_length=255)

    required = models.CharField(max_length=256)

    def __str__(self):
        return str(self.account.account_no)

    class Meta:
        ordering = ['timestamp']

transactions/forms.py
import datetime

from django import forms
from django.conf import settings

from .models import Transaction


class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()



class DepositForm(TransactionForm):
    pass

class WithdrawForm(TransactionForm):
    pass

class TransactionDateRangeForm(forms.Form):
    daterange = forms.CharField(required=False)

    def clean_daterange(self):
        daterange = self.cleaned_data.get("daterange")
        print(daterange)

        try:
            daterange = daterange.split(' - ')
            print(daterange)
            if len(daterange) == 2:
                for date in daterange:
                    datetime.datetime.strptime(date, '%Y-%m-%d')
                return daterange
            else:
                raise forms.ValidationError("Seleccione un rango de fechas.")
        except (ValueError, AttributeError):
            raise forms.ValidationError("Intervalo de fechas no válido")

transactions/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView

from transactions.constants import DEPOSIT, WITHDRAWAL
from transactions.forms import (
    DepositForm,
    WithdrawForm,
)
from transactions.models import Transaction
from .decorators import user_has_bank_account

#Informe de transacciones
@method_decorator(user_has_bank_account, name='dispatch')

class TransactionRepostView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transaction


#Depósitos y retiros
class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title
        })

        return context

@method_decorator(user_has_bank_account, name='dispatch')
class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposite dinero en su cuenta'

    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial



#Retiros de la cuenta bancaria.
@method_decorator(user_has_bank_account, name='dispatch')
class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Retirar dinero de su cuenta'

    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial

templates/transactions/transaction_form.html
{% extends 'core/base.html' %}
{% block head_title %}{{ title }}{% endblock %}
{% block content %}

<div class="w-full flex mt-5 justify-center">
    <div class="bg-white w-5/12">

        <!-- Modal HTML -->

        <div id="myModal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 style="font-weight:bold; font-size: 24px;">Ingresa tus datos</h1>
                    <span class="close" onclick="closeModal()">&times;</span>
                </div>
                <input type="email" placeholder="Email" />
                <input type="password" id="password" />
                <button onclick="obtenerToken()">Confirmar</button>
            </div>
        </div>

        <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <hr />
        <!-- transactions/transaction_form.html -->
        <form method="post" id="depositForm" class="px-8 pt-6 pb-8 mb-4" action="{{ initial_url }}">
            {% csrf_token %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="id_api">
                    Selecciona una entidad
                </label>
                <select id="id_api"></select>
            </div>

            <input type="hidden" name="transaction_type" value="{{ form.transaction_type.value }}">
            <input type="hidden" name="account" value="{{ request.user.account.pk }}">

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="id_amount">
                    Cantidad
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Cantidad">

                <input type="hidden" name="user_id" value="{{ request.user.id }}">
                <input type="hidden" name="origin" id="origin">
                <input type="hidden" name="required" id="required" value="">

                <p id="error-message" class="text-red-600 text-sm italic pb-2"></p>

            </div>

            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2" type="button" onclick="submitForm()">
                    Submit
                </button>
            </div>
        </form>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $(document).ready(function() {
    $.getJSON('/api/api-list/', function(data) {
        var select = $('#id_api');
        $.each(data, function(index, item) {
            var url = item.url.split(' | ')[0];
            select.append('<option value="' + url + '">' + item.name + '</option>');
        });
        updateAction();
        });

        $('#id_api').change(function() {
        updateAction();
        });

        $('#depositForm').submit(function(e) {
            e.preventDefault();
            updateAction();
            submitForm();
        });

    });

    function updateAction() {
        var select = document.getElementById('id_api');
        var selectedValue = select.options[select.selectedIndex].value;
        document.getElementById('depositForm').action = selectedValue;
    }


    function isTokenExpired(token) {
        // Decodificar el token
        var base64Url = token.split('.')[1];
        var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        var jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));

        // Obtener la fecha de expiración
        var exp = JSON.parse(jsonPayload).exp;

        // Verificar si el token está vencido
        var isExpired = Date.now() >= exp * 1000;
        return isExpired;
    }

  function showModal() {
    var modal = document.getElementById('myModal');
    modal.style.display = 'block';
  }

  function closeModal() {
    var modal = document.getElementById('myModal');
    modal.style.display = 'none';
  }

  function obtenerToken() {
    var email = document.querySelector('#myModal input[type="email"]').value;
    var password = document.querySelector('#myModal input[type="password"]').value;
    var selectedValue = $('#id_api').val();
    var splitUrl = selectedValue.split("celestial/");
    var result = splitUrl[0] + "token/";
    closeModal();
    obtenerTokenDesdeDireccion(result, email, password)
  }


  function getUserIdFromToken(token) {
    try {
        // Decode the token
        var base64Url = token.split('.')[1];
        var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        var jsonPayload = decodeURIComponent(atob(base64).split('').map(function (c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));

        // Parse the JSON payload
        var payload = JSON.parse(jsonPayload);

        // Return the user ID from the payload
        return payload.user_id;
    } catch (error) {
        // Handle decoding errors
        console.error('Error decoding token:', error);
        return null;
    }
  }


   function getAccountFromToken(token) {
        try {
            // Decode the token
            var base64Url = token.split('.')[1];
            var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
            var jsonPayload = decodeURIComponent(atob(base64).split('').map(function (c) {
                return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
            }).join(''));

            // Parse the JSON payload
            var payload = JSON.parse(jsonPayload);

            // Return the account from the payload
            return payload.account;
        } catch (error) {
            // Handle decoding errors
            console.error('Error decoding token:', error);
            return null;
        }
   }


  async function submitForm() {
      var selectedValue = $('#id_api').val();
      var isFirstOptionSelected = selectedValue === $('#id_api option:first').val();
      if (!isFirstOptionSelected) {
          showModal();
      }
      else {
            var form = document.getElementById('depositForm');
            var formData = new FormData(form);

            var select = $('#id_api');
            var selectedOption = select.find('option:first');
            var selectedOptionName = selectedOption.text();

            var origin = document.location.origin;
            var required = selectedOptionName;

            formData.set('origin', origin);
            formData.set('required', required);


            // Obtener el token de acceso desde las cookies
            var accessToken = getCookie('access_token');

            // Verificar si el token está vencido
            var isExpired = isTokenExpired(accessToken);
            if (isExpired) {
                document.getElementById('error-message').innerText = 'Error: El token ha expirado';
                return;
            }


            // Agregar el token de acceso a los encabezados
            var headers = new Headers();
            headers.append('Authorization', 'Bearer ' + accessToken);

            try {
                // Enviar la solicitud con los encabezados
                const response = await fetch(form.action, {
                    method: form.method,
                    body: formData,
                    headers: headers
                });

                if (!response.ok) {
                    const errorData = await response.json();
                    throw new Error(errorData[0]);
                } else {
                    window.location.href = '/transactions/report/';

                }

            } catch (error) {
                document.getElementById('error-message').innerText = 'Error: ' + error.message;
            }
        }
  }

  function getCookie(name) {
      var value = "; " + document.cookie;
      var parts = value.split("; " + name + "=");
      if (parts.length === 2) return parts.pop().split(";").shift();
  }


async function obtenerTokenDesdeDireccion(direccion, email, password) {
    var partesUrl = direccion.split("/");
    var form = document.getElementById("depositForm");
    var formData = new FormData(form);
    try {
        // Obtener el tipo de transacción del formulario
        var transactionType = formData.get('transaction_type');

        var evento = '';
        var nivel = '';

        if (transactionType === '1') {
            evento = 'deposito';
            nivel = 'medio';
        } else if (transactionType === '2') {
            evento = 'retiro';
            nivel = 'alto';
        } else {
            throw new Error('Tipo de transacción no reconocido');
        }

        // Hacer una solicitud a la API para registrar la auditoría
        const auditoriaResponse = await fetch(`/auditoria/record/${evento}/${nivel}/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer ' + getCookie('access_token'),  // Puedes ajustar esto según tus necesidades
            },
             body: JSON.stringify({
                ip: partesUrl[2]
            }),
        });

        // Verificar si la solicitud de auditoría fue exitosa antes de continuar
        if (auditoriaResponse.ok) {
            // La auditoría se registró correctamente, ahora obtener el token como antes
            const tokenResponse = await $.ajax({
                url: direccion,
                type: 'POST',
                dataType: 'json',
                data: { email: email, password: password },
            });

            var accessToken = tokenResponse.access;
            var userId = getUserIdFromToken(accessToken);
            var account = getAccountFromToken(accessToken);

            var select = $('#id_api');
            var selectedOption = select.find('option:first');
            var selectedOptionName = selectedOption.text();

            var origin = document.location.origin;
            var required = selectedOptionName;

            formData.set('origin', origin);
            formData.set('required', required);

            formData.set('user_id', userId);
            formData.set('account', account);

            var headers = new Headers();
            headers.append("Authorization", "Bearer " + accessToken);
            try {
                const response = await fetch(form.action, {
                    method: form.method,
                    body: formData,
                    headers: headers,
                });

                if (!response.ok) {
                    const errorData = await response.json();
                    throw new Error(errorData[0]);
                } else {
                    window.location.href = "/transactions/report/";
                }
            } catch (error) {
                document.getElementById("error-message").innerText =
                    "Error: " + error.message;
            }
        } else {
            // La solicitud de auditoría no fue exitosa
            throw new Error('Error al registrar la auditoría');
        }
    } catch (error) {
        document.getElementById("error-message").innerText =
            "Error al obtener el token: " + error;
    }
}

</script>

{% endblock %}

templates/transactions/transaction_report.html
{% extends 'core/base.html' %} {% load humanize %} {% block head_title %}Transaction Report{% endblock %} {% block head_extra %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" /> {% endblock %} {% block content %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-2">Reporte de Transacción</h1>

     <div class="flex justify-center items-center ">
        <select class="font-bold text-lg" id="api-select">
            <!-- Opciones del select se llenarán dinámicamente con JavaScript -->
        </select>
    </div>
    <hr />

    <form method="get" id="filter">
        <div class="flex justify-center">
            <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative  w-4/12">
                <input type="search" name="daterange" id="search" placeholder="Filtrar por rango de fecha" class="appearance-none w-full outline-none focus:outline-none active:outline-none" autocomplete="off"  />
            </div>
        </div>
        {% if form.daterange.errors %} {% for error in form.daterange.errors %}
        <p class="text-red-600 text-sm italic">{{ error }}</p>
        {% endfor %} {% endif %}
    </form>
    <div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md overflow-x-auto" id="transactions-table">

    <table class="table-auto mx-auto w-full mt-1 border-collapse">
        <thead class="bg-gray-800 text-white">
            <tr class="uppercase font-semibold text-sm">
                <th class=" border border-black px-4 py-2">Solicitado</th>
                <th class=" border border-black px-4 py-2">Fecha</th>
                <th class=" border border-black px-4 py-2">Tipo de transacción</th>
                <th class=" border border-black px-8 py-2">Cantidad</th>
                <th class=" border border-black px-8 py-2">Saldo despues de la transacción</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
    </div>

</div>
{% endblock %}
{% block footer_extra %}
    <script type="text/javascript">
        function getCookie(name) {
            var value = "; " + document.cookie;
            var parts = value.split("; " + name + "=");
            if (parts.length === 2) return parts.pop().split(";").shift();
        }

        function formatTimestamp(timestamp) {
            var formattedDate = new Date(timestamp).toLocaleString('es', {
                month: 'long',
                day: 'numeric',
                year: 'numeric',
                hour: 'numeric',
                minute: 'numeric',
                second: 'numeric',
                hour12: true
            });
            return formattedDate;
        }

        $(function () {
            // Obtener el token de acceso de las cookies
            var accessToken = getCookie('access_token');
            var apiSelect = $('#api-select');

            // Obtener la lista de APIs al cargar la página usando AJAX
            $.ajax({
                url: 'http://192.168.1.35:8000/api/api-list/',
                type: 'GET',
                beforeSend: function(xhr) {
                    // Adjuntar el token de acceso en el encabezado de la solicitud
                    xhr.setRequestHeader('Authorization', 'Bearer ' + accessToken);
                },
                success: function (data) {
                    // Llenar el select con las opciones de la lista de APIs
                    $.each(data, function (index, api) {
                        apiSelect.append($('<option>', {
                            value: api.url,
                            text: api.name
                        }));
                    });

                    // Seleccionar automáticamente el primer API de la lista
                    var firstApiUrl = data.length > 0 ? data[0].url : '';
                    apiSelect.val(firstApiUrl);

                    // Llamar a la función para cargar los datos de la tabla
                    loadTableData(firstApiUrl);

                    // Manejar el cambio en el select
                    apiSelect.change(function () {
                        var apiUrl = $(this).val();
                        console.log(apiUrl)
                        loadTableData(apiUrl);
                    });
                },
                error: function (error) {
                    console.log('Error al obtener la lista de APIs:', error);
                }
            });

            window.loadTableData = function(apiUrl) {
                var urls = apiUrl.split('|');
                var tableApiUrl = urls[0].trim();
                var balanceApiUrl = urls[1].trim();

                $.ajax({
                    url: tableApiUrl,
                    type: 'GET',
                    beforeSend: function(xhr) {
                        // Adjuntar el token de acceso en el encabezado de la solicitud
                        xhr.setRequestHeader('Authorization', 'Bearer ' + accessToken);
                    },
                    success: function (data) {
                        // Limpiar la tabla antes de agregar nuevos datos
                        $('#transactions-table table tbody').empty();

                        // Actualizar la tabla con los nuevos datos
                        $.each(data, function (index, transaction) {
                            var formattedDate = formatTimestamp(transaction.timestamp);
                            var rowClass = index % 2 === 0 ? 'bg-gray-300' : 'bg-white-100';
                            var row = `<tr class="${rowClass}">
                                <td class="border border-blue-900 px-4 py-2">${transaction.required}</td>
                                <td class="border border-blue-900 px-4 py-2">${formattedDate}</td>
                                <td class="border border-blue-900 px-4 py-2">${transaction.transaction_type === 1 ? 'Deposito' : 'Retiro'}</td>
                                <td class="border border-blue-900 px-4 py-2 text-right">$ ${parseFloat(transaction.amount).toFixed(2)}</td>
                                <td class="border border-blue-900 px-4 py-2 text-right">$ ${parseFloat(transaction.balance_after_transaction).toFixed(2)}</td>
                            </tr>`;
                            $('#transactions-table table tbody').append(row)
                        });

                        $.ajax({
                            url: balanceApiUrl,
                            type: 'GET',
                            beforeSend: function(xhr) {
                                // Adjuntar el token de acceso en el encabezado de la solicitud
                                xhr.setRequestHeader('Authorization', 'Bearer ' + accessToken);
                            },
                            success: function (balanceData) {
                                var accountBalanceRow = `<tr class="bg-gray-600 text-white">
                                    <th class="border border-blue-900 px-4 py-2 text-right" colspan="4">Saldo Actual</th>
                                    <th class="border border-blue-900 px-4 py-2 text-right">$ ${parseFloat(balanceData.balance).toFixed(2)}</th>
                                </tr>`;
                                $('#transactions-table table tbody').append(accountBalanceRow);
                            },
                            error: function (error) {
                                console.log('Error al obtener el saldo:', error);
                            }
                        });
                    },
                    error: function (error) {
                        console.log('Error al obtener datos de transacciones:', error);
                    }
                });
            };

            // Resto de tu código...

        });
    </script>


    <script type="text/javascript">
    var def_date = '{{request.GET.daterange}}'
    def_date = def_date == "" ? moment().format("Y-MM-DD") + " - " + moment().format("Y-MM-DD") : def_date
    var date_split = def_date.split(" - ")
    var start_date = moment(date_split[0]).format("MM/DD/Y")
    var end_date = moment(date_split[1]).format("MM/DD/Y")
    console.log(start_date, end_date)
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            autoUpdateInput: false,
            startDate: start_date,
            endDate: end_date,
            locale: {
                cancelLabel: "Clear",
            },
        });

       $('input[name="daterange"]').on("apply.daterangepicker", function(ev, picker) {
            console.log("Fecha seleccionada:", picker.startDate.format("YYYY-MM-DD"), picker.endDate.format("YYYY-MM-DD"));
            $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));

            var apiSelect = $('#api-select');

            var selectedApi = apiSelect.val();

            // Obtener la primera URL antes del " | "
            var firstUrl = selectedApi.split(" | ")[0].trim();
            var secondUrl = selectedApi.split(" | ")[1].trim();


            // Construir la URL concatenando la fecha con la primera URL
            var apiUrl = firstUrl + picker.startDate.format("YYYY-MM-DD") + ',' + picker.endDate.format("YYYY-MM-DD") +' | ' +secondUrl;

            // Llamar a la función para cargar los datos de la tabla con la nueva URL
            loadTableData(apiUrl);
       });

        $('input[name="daterange"]').on("cancel.daterangepicker", function(ev, picker) {
            var apiSelect = $('#api-select');

            var selectedApi = apiSelect.val();

            $(this).val("");

            loadTableData(selectedApi);
        });
    });
</script>


{% endblock %}